### ISSUE TITLE
错误信息没有正确返回给onebot

### ISSUE THREAD

**Issue by SlightDust** [super1207/KookOneBot#4]
背景：今天（2023.10.23）一部分（或者全部）bot无法发送图片，频道内发送图片会收到`由于服务器维护，暂时无法 进行此操作，带来不便请谅解`的返回。这个错误信息没有返回到onebot  

kookonebot这边的日志
```
2023-10-23 20:30:00.977  INFO kook_onebot::kook_onebot: 发送KOOK_POST:/message/create
{"content":"https://img.kookapp.cn/attachments/2023-10/22/xxxxxxxxxxxxxx.png","target_id":"4843263199681351","type":2}

2023-10-23 20:30:01.192  INFO kook_onebot::kook_onebot: KOOK_POST响应:{"code":40000,"message":"由于服务器维护，暂时无法 进行此操作，带来不便请谅解","data":{"name":"Bad Request","status":400}}
2023-10-23 20:30:01.192 ERROR kook_onebot::onebot_ws_rev: ONEBOT_WS_REV动作调用出错:Err("msg_id not found")
```

nonebot报WebSocket API call timeout
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 104, in fetch
    return await asyncio.wait_for(future, timeout_sec)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/HoshinoBot_yubao_KOOK/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot_yubao_KOOK/hoshino/service.py", line 224, in wrapper
    return await func(bot, event)
  File "/root/HoshinoBot_yubao_KOOK/hoshino/modules/kaiheila/kaiheila.py", line 121, in kaiheila_server_status
    await bot.send(ev, msg)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 108, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout
```

**Comment by super1207** [comment]
已经修正，应该已经不会因为发送消息失败而导致超时了。（暂时先到github action中去下载测试
https://github.com/super1207/KookOneBot/commit/0e47f867421941905d7fb5a7a61f6571aefc3266

**Comment by SlightDust** [comment]
验证OK~不会超时了
